version: 1.0
os: linux
files:
  - source: target/cloudshape-1.0.0.jar
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 3600
  ApplicationStop:
  - location: scripts/application-stop.sh
      timeout: 3600
